POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjZlZGJlMjMxZmU1YzEwMWEyYzdmMCIsInVzZXJuYW1lIjoiajgiLCJpYXQiOjE2MzQxMzYxMTAsImV4cCI6MTYzNDc0MDkxMH0.2j3xiYbL6XpDO6pHH1_luUSjEn9S4qrxwa4LLNejOQ8

{
"content": "otra nueva nota", 
"important": true
}